### ISSUE TITLE
Errors on first run

### ISSUE THREAD

**Issue by Germs2004** [QuantumObject/docker-zoneminder#85]
I'm trying to get this working but the README doesn't seem to work.  It doesn't say that I have to specify "MYSQL_ROOT" and "MYSQL_ROOT_PASSWORD" but if I don't, it can't create the zm database.  When I do specify those, it creates the zm database and zmuser, but it still gets errors saying the zmuser can't connect.  Also, if I try to specify a different db name, like "zoneminder" instead of "zm", the initial setup script still creates the database as "zm" and then later gets errors when it tries to connect to "zoneminder" which doesn't exist.

Generally seems like the setup process could use some testing of all the variables, and the documentation could use some updates to include everything a user needs to get zoneminder up and running in docker.

my docker create command:
```
	docker create -t \
	  --name zoneminder \
	  --restart=unless-stopped \
	  -p 1080:80 \
	  -p 1081:443 \
	  -e TZ='America/New_York' \
	  -e ZM_DB_HOST=$dbdockercontainername \
	  -e ZM_DB_NAME=$NEWDBNAME \
	  -e ZM_DB_USER=$NEWDBUSERNM \
	  -e ZM_DB_PASS=$NEWDBUSERPW \
	  -e ZM_DB_PORT=3306 \
	  -e MYSQL_ROOT=$ROOTUSR \
	  -e MYSQL_ROOT_PASSWORD=$ROOTPWD \
	  -v /home/me/zoneminder/events:/var/lib/zoneminder/events \
	  -v /home/me/zoneminder/logs:/var/log/zm \
	  --shm-size="512m" \
	  --net db-network \
	  quantumobject/docker-zoneminder:latest
```

the docker logs during first run:
```
Starting pre-service scritps in /etc/my_init.d

*** Running: /etc/my_init.d/startup.sh

mysql: [Warning] Using a password on the command line interface can be insecure.

mysql: [Warning] Using a password on the command line interface can be insecure.

mysql: [Warning] Using a password on the command line interface can be insecure.

DBI connect('database=zm;host=mariadb','zmuser',...) failed: Access denied for user 'zmuser'@'zoneminder.db-network' (using password: YES) at /usr/share/perl5/ZoneMinder/Database.pm line 110.

DBI connect('database=zm;host=mariadb','zmuser',...) failed: Access denied for user 'zmuser'@'zoneminder.db-network' (using password: YES) at /usr/share/perl5/ZoneMinder/Database.pm line 110.

03/15/20 22:31:51.172570 zmupdate[124].ERR [ZoneMinder::Database:113] [Error reconnecting to db: errstr:Access denied for user 'zmuser'@'zoneminder.db-network' (using password: YES) error val:]

03/15/20 22:31:51.173733 zmupdate[124].ERR [ZoneMinder::Database:113] [Error reconnecting to db: errstr:Access denied for user 'zmuser'@'zoneminder.db-network' (using password: YES) error val:]

DBI connect('database=zm;host=mariadb','zmuser',...) failed: Access denied for user 'zmuser'@'zoneminder.db-network' (using password: YES) at /usr/share/perl5/ZoneMinder/Database.pm line 110.

03/15/20 22:31:51.177851 zmupdate[124].ERR [ZoneMinder::Database:113] [Error reconnecting to db: errstr:Access denied for user 'zmuser'@'zoneminder.db-network' (using password: YES) error val:]

Can't call method "prepare_cached" on an undefined value at /usr/share/perl5/ZoneMinder/Config.pm line 96.

BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 147.

Compilation failed in require at /usr/bin/zmupdate.pl line 73.

BEGIN failed--compilation aborted at /usr/bin/zmupdate.pl line 73.

*** Failed with return value: 255
```

**Comment by angelrr7702** [comment]
DBD::mysql::st execute failed: Table 'zm1.Config' doesn't exist at /usr/share/perl5/ZoneMinder/Config.pm line 97.
Can't execute: Table 'zm1.Config' doesn't exist at /usr/share/perl5/ZoneMinder/Config.pm line 147.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 147.
Compilation failed in require at /usr/bin/zmupdate.pl line 73.
BEGIN failed--compilation aborted at /usr/bin/zmupdate.pl line 73.
*** Failed with return value: 255

**Comment by angelrr7702** [comment]
cat -n /usr/share/zoneminder/db/zm_create.sql | grep zm
     3	-- Host: localhost Database: zm
    17	-- Current Database: `zm`
    20	CREATE DATABASE /*!32312 IF NOT EXISTS*/ `zm`;
    22	USE `zm`;

**Comment by angelrr7702** [comment]
fix the problem relate to database name .,   building image for docker hub ,,, please test if that fix all the problem ..

**Comment by Germs2004** [comment]
Thanks for taking a look at this.

For clarity, here's the list of issues I've found with the first image I tested yesterday:
1) can't change the database name to anything other than "zm" or we get errors
2) must pass in the mariadb "root" user's password via MYSQL_ROOT_PASSWORD or we get errors.  I guess root permissions would be necessary if it had to create a new database, but if a blank database already exists and the ZM_DB_USER I passed in has full permissions on that database, is it possible for your script to detect the blank database and just fill in the tables from there without requiring root permissions?
3) (if I remember correctly) the script doesn't seem to handle when the database already exists during the container's first run. It always tries to recreate the database on the container's first run.
4) on subsequent runs, if the database is missing (because I deleted it), the script does not detect that and recreate the database.  I have to delete the Docker container and create a fresh one so that it thinks it's the "first run" again to create the database.
-------------------------------
I tested the new image you released today:

ID	sha256:186e42fd9104674f26653ac499871a4b5407341a1daaa107f8a8c892d6a66b9d  
Created	2020-03-11 11:56:36
Build	Docker 18.03.1-ee-3 on linux, amd64

**First test:
I passed in the root user credentials via MYSQL_ROOT_PASSWORD and did not manually create the database or sql user.**
It did not create the database or sql user on first run.  Even though I'll probably never want to pass in my root password, some of your users might want to on their first run to make things easier for them.  So if the user passes in MYSQL_ROOT_PASSWORD, you should problably create the database and user if they don't already exist, or fill in the database if it exists but is completely empty.
```
Starting pre-service scritps in /etc/my_init.d

*** Running: /etc/my_init.d/startup.sh

mysql: [Warning] Using a password on the command line interface can be insecure.

mysql: [Warning] Using a password on the command line interface can be insecure.

ERROR 1049 (42000): Unknown database 'zm123'

*** Failed with return value: 1
```

**Second test:
I passed in the root user credentials via MYSQL_ROOT_PASSWORD and DID manually create a database named zm and sql user myzmuser (with % source permission).**
This time, the container filled in all the missing tables into the blank database.  That's good.
However, it also created a new sql user even though I had already pre-created the user.  The user I created has "%" source permission, and the user your script created has "mariadb" (my sql server's hostname) source permission.

**Third test:
I passed in the root user credentials via MYSQL_ROOT_PASSWORD and DID manually create database named zm and sql user myzmuser (with mariadb source permission).**
This time, it filled in the empty database again, which is good.  It did not create a duplicate user this time, which is good.  But I saw errors in the Docker log, probably related to the sql user I created:
```
Starting pre-service scritps in /etc/my_init.d

*** Running: /etc/my_init.d/startup.sh

mysql: [Warning] Using a password on the command line interface can be insecure.

mysql: [Warning] Using a password on the command line interface can be insecure.

mysql: [Warning] Using a password on the command line interface can be insecure.

DBI connect('database=zm;host=mariadb','myzmuser',...) failed: Access denied for user 'myzmuser'@'zoneminder.db-network' (using password: YES) at /usr/share/perl5/ZoneMinder/Database.pm line 110.

DBI connect('database=zm;host=mariadb','myzmuser',...) failed: Access denied for user 'myzmuser'@'zoneminder.db-network' (using password: YES) at /usr/share/perl5/ZoneMinder/Database.pm line 110.

03/16/20 14:41:19.583010 zmupdate[129].ERR [ZoneMinder::Database:113] [Error reconnecting to db: errstr:Access denied for user 'myzmuser'@'zoneminder.db-network' (using password: YES) error val:]

03/16/20 14:41:19.583281 zmupdate[129].ERR [ZoneMinder::Database:113] [Error reconnecting to db: errstr:Access denied for user 'myzmuser'@'zoneminder.db-network' (using password: YES) error val:]

DBI connect('database=zm;host=mariadb','myzmuser',...) failed: Access denied for user 'myzmuser'@'zoneminder.db-network' (using password: YES) at /usr/share/perl5/ZoneMinder/Database.pm line 110.

03/16/20 14:41:19.584783 zmupdate[129].ERR [ZoneMinder::Database:113] [Error reconnecting to db: errstr:Access denied for user 'myzmuser'@'zoneminder.db-network' (using password: YES) error val:]

Can't call method "prepare_cached" on an undefined value at /usr/share/perl5/ZoneMinder/Config.pm line 96.

BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 147.

Compilation failed in require at /usr/bin/zmupdate.pl line 73.

BEGIN failed--compilation aborted at /usr/bin/zmupdate.pl line 73.

*** Failed with return value: 255
```

**Fourth Test:
I did NOT pass in the root user credentials via MYSQL_ROOT_PASSWORD and DID manually create database named zm123 and sql user zmuser123 (with % source permission).**
It did not fill in the missing tables or create a duplicate user.  In this case, I expected it to use the pre-existing blank database and user credentials that I passed in, and fill in the missing tables like normal.  I'm not sure why it is still trying to use the "root" user account or why it needs to since the user I created already has permissions to create tables on that blank database.
I saw these errors in the Docker log:
```
Starting pre-service scritps in /etc/my_init.d

*** Running: /etc/my_init.d/startup.sh

mysql: [Warning] Using a password on the command line interface can be insecure.

ERROR 1045 (28000): Access denied for user 'root'@'zoneminder.db-network' (using password: YES)

*** Failed with return value: 1
```

------------------------

I hope this gives an idea of what I'm trying to do so that you can try to test it on your side as you develop: create a docker container that does not know my root user credentials, and create a blank database and zm user.  Then the container should run and fill in the missing tables using the sql user I provided.  Also, test with non-default database names and sql user names.  Also, try doing a first run with the database and/or user already existing, and try doing a subsequent run with the database and/or user missing.  I think if you fix the errors in those situations, it will make this image much easier for new users to use.

Thanks again for working on this!  It's a very useful project because the official zoneminder docker image didn't work at all when I tested it.

**Comment by Germs2004** [comment]
While testing other things on a working install, I noticed that if I delete the docker container, but keep the database on my external database server, and then recreate the docker container, that new docker container will overwrite my database.  That's really bad because it erased all my customized config settings and presumably would have erased all my camera setups if I had any.  The database should be considered persistent data between container instances, and should never be overwritten, even if the docker container believes it's running for the first time (unless the database is completely empty with zero tables, in which case it should create all the missing tables like a fresh install). 
Thank you

**Comment by angelrr7702** [comment]
new build for container fix the last problem ., plus another error relate to /var/cache/zoneminder folder.

**Comment by angelrr7702** [comment]
new provisional container build at docker hub to test without root and root password for zoneminder .
quantunobject/docker-zoneminder:fix  

required to add --sql-mode="" to docker run command for mysql database or mariadb and  MYSQL_USER and MYSQL_PASSWORD  plus the full permission to modified the database create for zoneminder .  

example : 

docker run -d -e TZ=America/New_York -e MYSQL_USER=zmuser -e MYSQL_PASSWORD=zmpass -e MYSQL_DATABASE=zm -e MYSQL_ROOT_HOST=% --net net --name db mysql/mysql-server:5.7 --sql-mode=""

docker run -d --shm-size=4096m -e TZ=America/New_York -e ZM_DB_HOST=db --net net --name zm -p 80:80 quantumobject/docker-zoneminder:fix

when done testing modification will be  move to master and 1.34 and 1.32 version .

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
fix move to master and 1.32. and 1.34 container version . You don't need MYSQL_ROOT_PASSWORD anymore to deploy container .

**Comment by Germs2004** [comment]
It seems to be improving in some ways.  Now, it fills my empty database without requiring sql root rights, and it does not create a zmuser sql account for me.  I like that because I can easily create the empty database and user with a simple script before running this zoneminder docker image.  Good job.  I also like that it has a few volumes pre-assigned to store persistent data, though I had to assign a volume name to mine or else the image would create brand new volumes with random filenames every time I created a new container, and I ended up with over 100 of them.

However, with the latest dockerhub image, I get these messages in the docker log on first run with an empty database:
```
Starting pre-service scritps in /etc/my_init.d
*** Running: /etc/my_init.d/startup.sh
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1419 (HY000) at line 3 in file: '/usr/share/zoneminder/db/triggers.sql': You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)
*** Failed with return value: 1
Starting pre-service scritps in /etc/my_init.d
*** Running: /etc/my_init.d/startup.sh
mysql: [Warning] Using a password on the command line interface can be insecure.
already configured.
starting rc.local scritps
Booting runit daemon...
Process runsvdir running with PID 234
```

And when I access the site, it opens the login page right away (the older image would begin with a data sharing page).  The login page seems to be stuck in a javascript loop that constantly refreshes the page, putting my CPU at 100%.  If I enter admin;admin and click Login, nothing happens.  It just continues with the infinite loop.

This was my command:

```
docker create \
	  --name zoneminder \
	  --restart=unless-stopped \
	  -p 1080:80 \
	  -p 1081:443 \
	  -e TZ=America/New_York \
	  -e ZM_DB_HOST=$DatabaseContainerName \
	  -e ZM_DB_PORT=$DatabaseContainerPort \
	  -e ZM_DB_NAME=$NEWDBNAME \
	  -e ZM_DB_USER=$NEWDBUSERNM \
	  -e ZM_DB_PASS=$NEWDBUSERPW \
	  -v zoneminder_config:/config \
	  -v zoneminder_etc:/etc/zm \
	  -v zoneminder_cache:/var/cache/zoneminder \
	  -v zoneminder_log:/var/log/zm \
	  --net db-network \
	  --shm-size=4096m \
	  quantumobject/docker-zoneminder:latest
```

Here's the image I used for this test:
```
ID | sha256:6a2c39fe64bc4c95451ea26dea527a78f2dc26aad4a01fd6bced23029be0745e
Created | 2020-03-18 23:51:43
Build | Docker 18.03.1-ee-3 on linux, amd64
```

**Comment by angelrr7702** [comment]
did you added the sql-mode=""  when creating the database ? 

By 

docker run -d -e TZ=xxxxx -e MYSQL_USER=xxxx -e MYSQL_PASSWORD=xxxxxx -e MYSQL_DATABASE=xxx -e MYSQL_ROOT_HOST=% --net net --name db mysql/mysql-server:5.7 --sql-mode=""

or by change  MYSQL setting /etc/mysql/my.cnf

sql_mode = NO_ENGINE_SUBSTITUTION

normally this was done inside the zoneminder container but after removing the MYSQL_ROOT_PASSWORD impossible , the database you create already have to be ready with the right  configuration and  permission for MYSQL_USER to modified  it .

plus for some version of MYSQL container  I found that you need to used -e MYSQL_RANDOM_ROOT_PASSWORD=yes if you don't define root password . 

but maybe the problem can be relate to  -v zoneminder_etc:/etc/zm    that I will check if need to create a redundancy when the first time used . 

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
yes, appear if you use -v zoneminder_etc:/etc/zm  the container complete failed ... no idea how you was able to running with error .. maybe you already have some data from other re-run of container.

I have to think about a fix for it .. will take some time ...

**Comment by angelrr7702** [comment]
done with last fix .. that make sure that we have conf files at /etc/zm  and make sure that permission is correct at all folder in volume .

**Comment by Germs2004** [comment]
> did you added the sql-mode="" when creating the database ?
> docker run -d -e TZ=xxxxx -e MYSQL_USER=xxxx -e MYSQL_PASSWORD=xxxxxx -e MYSQL_DATABASE=xxx -e MYSQL_ROOT_HOST=% --net net --name db mysql/mysql-server:5.7 --sql-mode=""
> or by change MYSQL setting /etc/mysql/my.cnf
> sql_mode = NO_ENGINE_SUBSTITUTION

No, I read that was only necessary if you are using MySQL and ZoneMinder < v1.32.  [This link](https://readthedocs.org/projects/zoneminder/downloads/pdf/latest/) says:
```
Certain new defaults in MySQL 5.7 cause some issues with ZoneMinder < 1.32.0, the workaround is to modify the sql_mode setting of MySQL. Please note that these changes are NOT required for ZoneMinder 1.32.0 and some people have reported them causing problems in 1.32.0.
```

I'm using MariaDB and ZoneMinder 1.34, so it seems that changing the sql_mode is not necessary.

I tested everything with your latest image, and still have the same problem.  When the ZM website loads for the first time, the login page appears and it keeps refreshing itself over and over very quickly.  I see a message flash on the screen repeatedly that says something like "waiting for cache".

**Comment by angelrr7702** [comment]
for mysql 8 ==>

sudo docker run -d -e TZ=America/New_York -e MYSQL_USER=zmuser -e MYSQL_PASSWORD=zmpass -e MYSQL_DATABASE=zm1 -e MYSQL_ROOT_HOST=% -e MYSQL_RANDOM_ROOT_PASSWORD=yes --net net --name database mysql/mysql-server --disable-log-bin --default-authentication-plugin=mysql_native_password

sudo docker run -d --shm-size=4096m -e TZ=America/New_York -e ZM_DB_HOST=database -e ZM_DB_NAME=zm1 --net net --name zm  -p 80:80 quantumobject/docker-zoneminder

In this case , the important part is  --disable-log-bin --default-authentication-plugin=mysql_native_password  , Apparently this is because mySQL 8 uses a different method of authentication by default .

Appear that the same for mariadb : 

sudo docker run -d -e TZ=America/New_York -e MYSQL_USER=zmuser -e MYSQL_PASSWORD=zmpass -e MYSQL_DATABASE=zm1 -e MYSQL_ROOT_HOST=% -e MYSQL_RANDOM_ROOT_PASSWORD=yes --net net --name database mariadb --disable-log-bin --default-authentication-plugin=mysql_native_password

That work for me .

sincerely
Angel Rodriguez

**Comment by Germs2004** [comment]
If I add sql_mode="" to my mariadb container, it puts an error in the docker log that basically says it doesn't recognize that, and then that mariadb container just keeps restarting itself.  Also, consider that your ZM image was working better in one of your recent revisions (without having to use sql_mode), but now it has gotten worse for me.  So I think the problem is not related to sql_mode, but something else related to the scripts on that login page.

With the latest image, I still have the constantly refreshing ZM login page.  And I see lots of errors like these in the container's /var/log/apache2/error.log:
```
[Tue Mar 24 14:40:19.307338 2020] [php7:warn] [pid 10502] [client 192.168.4.101:61633] PHP Warning:  A non-numeric value encountered in /usr/share/zoneminder/www/skins/classic/js/skin.js.php on line 29
[Tue Mar 24 14:40:19.307351 2020] [php7:warn] [pid 10502] [client 192.168.4.101:61633] PHP Warning:  Use of undefined constant ZM_OPT_USE_AUTH - assumed 'ZM_OPT_USE_AUTH' (this will throw an Error in a future version of PHP) in /usr/share/zoneminder/www/skins/classic/js/skin.js.php on line 74
[Tue Mar 24 14:40:19.307358 2020] [php7:warn] [pid 10502] [client 192.168.4.101:61633] PHP Warning:  Use of undefined constant ZM_AUTH_HASH_LOGINS - assumed 'ZM_AUTH_HASH_LOGINS' (this will throw an Error in a future version of PHP) in /usr/share/zoneminder/www/skins/classic/js/skin.js.php on line 74
[Tue Mar 24 14:40:19.307364 2020] [php7:warn] [pid 10502] [client 192.168.4.101:61633] PHP Warning:  Use of undefined constant ZM_AUTH_HASH_IPS- assumed 'ZM_AUTH_HASH_IPS' (this will throw an Error in a future version of PHP) in /usr/share/zoneminder/www/skins/classic/js/skin.js.php online 75
```

I know I have posted lots of errors here recently, and you've been working hard to fix them for me, but I'm ready to give up on this docker image.  It just doesn't seem production ready yet, so maybe I'll come check on it again in a year or so.  Thank you for your hard work anyway.

I'll leave you with snippets from my install scripts, in case you are still interested in figuring out what's wrong and testing with mariadb.
```
# Docker image: mariadb
# https://hub.docker.com/r/linuxserver/mariadb/
response=""
while [[ $response != "y" && $response != "n" ]]
do
read -p "Do you want to install docker image: mariadb? [y/n] " response
done

if [[ $response == "y" ]]; then
	
	# Create "db-network" if it does not exist.
	NetworkName="db-network"
	NetworkIsMissing=$(sudo docker network ls|grep $NetworkName > /dev/null; echo "$?")
	if [[ $NetworkIsMissing == 1 ]]; then
		printf "\n${YELLOW}Network \"$NetworkName\" does not exist. Creating it now...${NORMAL}\n"
		docker network create -d bridge db-network
	else
		printf "Network \"$NetworkName\" already exists.\n"
	fi
	
	
	# Download and create the Docker container
	printf "\n${YELLOW}Making sure we have the latest Docker image available...${NORMAL}\n"
	docker pull linuxserver/mariadb:latest
	
	printf "\n${YELLOW}Creating container: mariadb...${NORMAL}\n"

	docker create \
	  --name mariadb \
	  --restart=unless-stopped \
	  --network $NetworkName \
	  -e PUID=1000 \
	  -e PGID=1000 \
	  -e MYSQL_ROOT_PASSWORD=jFtwnOdfg1Sts78QIIMxmfd \
	  -e TZ=America/New_York \
	  -p 3306:3306 \
	  -v /home/jeremy/mariadb/:/config \
	  linuxserver/mariadb:latest
	
	
	printf "\n${YELLOW}Starting the container now...${NORMAL}\n"  
	docker start mariadb

	printf "\n${YELLOW}Complete.  Access at localhost:3306${NORMAL}\n"
fi





# Docker image: ZoneMinder (camera software)
response=""
while [[ $response != "y" && $response != "n" ]]
do
read -p "Do you want to install docker image: ZoneMinder? [y/n] " response
done

if [[ $response == "y" ]]; then

	# create database and user if they don't exist
	DatabaseContainerName="mariadb"
	DatabaseContainerPort=3306
	ROOTUSR="root"
	ROOTPWD="jFtwnOdfg1Sts78QIIMxmfd"
	NEWDBNAME="zoneminder"
	NEWDBUSERNM="myzmuser"
	NEWDBUSERPW="Lxo53p94sasdyU1uZ8AH4sTaOHjKSahRb"
		
	NEWDBMISSING=$(sudo docker exec -i $DatabaseContainerName mysql -u$ROOTUSR -p$ROOTPWD --batch --skip-column-names -e "SHOW DATABASES LIKE '"$NEWDBNAME"';" | grep "$NEWDBNAME" > /dev/null; echo "$?")
	if [[ $NEWDBMISSING == 1 ]]; then
		printf "\n${YELLOW}Creating new database and user: $NEWDBNAME${NORMAL}\n"
		docker exec -i $DatabaseContainerName mysql -u$ROOTUSR -p$ROOTPWD -e "CREATE DATABASE ${NEWDBNAME};"
		docker exec -i $DatabaseContainerName mysql -u$ROOTUSR -p$ROOTPWD -e "CREATE USER '${NEWDBUSERNM}'@'%' IDENTIFIED BY '${NEWDBUSERPW}';"
		docker exec -i $DatabaseContainerName mysql -u$ROOTUSR -p$ROOTPWD -e "GRANT ALL PRIVILEGES ON ${NEWDBNAME}.* TO '${NEWDBUSERNM}'@'%';"
		docker exec -i $DatabaseContainerName mysql -u$ROOTUSR -p$ROOTPWD -e "FLUSH PRIVILEGES;"
	else
		printf "\n${YELLOW}Database already exists: $NEWDBNAME${NORMAL}\n"
	fi
	
	
	# Create "db-network" if it does not exist.
	NetworkName="db-network"
	NetworkIsMissing=$(sudo docker network ls|grep $NetworkName > /dev/null; echo "$?")
	if [[ $NetworkIsMissing == 1 ]]; then
		printf "\n${YELLOW}Network \"$NetworkName\" does not exist. Creating it now...${NORMAL}\n"
		docker network create -d bridge db-network
	else
		printf "Network \"$NetworkName\" already exists.\n"
	fi
	
	
	# Download and create the Docker container
	printf "\n${YELLOW}Making sure we have the latest Docker image available...${NORMAL}\n"
	docker pull quantumobject/docker-zoneminder:latest
	
	
	printf "\n${YELLOW}Creating container: ZoneMinder...${NORMAL}\n"



	docker create \
	  --name zoneminder \
	  --restart=unless-stopped \
	  --network $NetworkName \
	  -p 1080:80 \
	  -p 1081:443 \
	  -e TZ=America/New_York \
	  -e ZM_DB_HOST=$DatabaseContainerName \
	  -e ZM_DB_PORT=$DatabaseContainerPort \
	  -e ZM_DB_NAME=$NEWDBNAME \
	  -e ZM_DB_USER=$NEWDBUSERNM \
	  -e ZM_DB_PASS=$NEWDBUSERPW \
	  -v zoneminder_config:/config \
	  -v zoneminder_etc:/etc/zm \
	  -v zoneminder_cache:/var/cache/zoneminder \
	  -v zoneminder_log:/var/log/zm \
	  --shm-size=4096m \
	  quantumobject/docker-zoneminder:latest
	
	

	printf "\n${YELLOW}Starting the container now...${NORMAL}\n"  
	docker start zoneminder
	
	printf "\n${YELLOW}Complete.  Now access the site at http://localhost:1080/zm${NORMAL}\n"
fi
```

**Comment by angelrr7702** [comment]
please check the last few entry from my response and update to documentation  . zoneminder don't used recently change to security login at database in mariadb and mysql .... need to add the -disable-log-bin --default-authentication-plugin=mysql_native_password  option to run database container .
